### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SergeyDavidovich** [SergeyDavidovich/WebCalc#12]
**Is it right that file IConstantRepository.cs contains interface IRepository<T>?**

**Comment by BekAllaev** [comment]
Hi @SergeyDavidovich. No, it is no right. First of all thank you, you have found the problem. Was fixed in this commit - [link](https://github.com/SergeyDavidovich/WebCalc/commit/507985850ce0fd7c8eef8daed60caa805efb35fa)
